# Generated by Django 5.2.13 on 2026-04-29 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import web.api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        default=web.api.models.uuid_string, max_length=120, unique=True
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("processing", "Processing"),
                            ("review_ready", "Review ready"),
                            ("engine_ready", "Engine ready"),
                            ("committed", "Committed"),
                        ],
                        default="draft",
                        max_length=40,
                    ),
                ),
                (
                    "data_origin",
                    models.CharField(
                        choices=[("synthetic", "Synthetic"), ("real_derived", "Real-derived")],
                        default="real_derived",
                        max_length=40,
                    ),
                ),
                ("reviewed_state", models.JSONField(blank=True, default=dict)),
                ("readiness", models.JSONField(blank=True, default=dict)),
                ("match_candidates", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_workspaces",
                        to="api.household",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("original_filename", models.CharField(max_length=500)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("extension", models.CharField(blank=True, max_length=20)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(max_length=64)),
                ("storage_path", models.CharField(blank=True, max_length=1000)),
                ("document_type", models.CharField(default="unknown", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("duplicate", "Duplicate"),
                            ("classified", "Classified"),
                            ("text_extracted", "Text extracted"),
                            ("ocr_required", "OCR required"),
                            ("ocr_complete", "OCR complete"),
                            ("facts_extracted", "Facts extracted"),
                            ("reconciled", "Reconciled"),
                            ("unsupported", "Unsupported"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=40,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("processing_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="api.reviewworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("process_document", "Process document"),
                            ("reconcile_workspace", "Reconcile workspace"),
                        ],
                        default="process_document",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=40,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="api.reviewdocument",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="api.reviewworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("field", models.CharField(max_length=255)),
                ("value", models.JSONField(default=dict)),
                ("asserted_at", models.DateField(blank=True, null=True)),
                (
                    "confidence",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "derivation_method",
                    models.CharField(
                        choices=[
                            ("extracted", "Extracted"),
                            ("inferred", "Inferred"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="extracted",
                        max_length=20,
                    ),
                ),
                ("source_page", models.PositiveIntegerField(blank=True, null=True)),
                ("source_location", models.CharField(blank=True, max_length=255)),
                ("evidence_quote", models.TextField(blank=True)),
                ("extraction_run_id", models.CharField(max_length=255)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_facts",
                        to="api.reviewdocument",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_facts",
                        to="api.reviewworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["field", "-asserted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SectionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("section", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("approved_with_unknowns", "Approved with unknowns"),
                            ("needs_attention", "Needs attention"),
                            ("not_ready_for_recommendation", "Not ready for recommendation"),
                        ],
                        default="needs_attention",
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="section_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_approvals",
                        to="api.reviewworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["section"],
            },
        ),
        migrations.CreateModel(
            name="ReviewedClientStateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "schema_version",
                    models.CharField(default="reviewed_client_state.v1", max_length=40),
                ),
                ("state", models.JSONField(default=dict)),
                ("readiness", models.JSONField(default=dict)),
                ("is_committed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "committed_household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_state_versions",
                        to="api.household",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_state_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_versions",
                        to="api.reviewworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "version"), name="unique_state_version"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reviewdocument",
            constraint=models.UniqueConstraint(
                fields=("workspace", "sha256"), name="unique_review_document_workspace_sha"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionapproval",
            constraint=models.UniqueConstraint(
                fields=("workspace", "section"), name="unique_section_approval"
            ),
        ),
    ]
