# Generated by Django 5.2.13 on 2026-04-29 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import web.api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_workerheartbeat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="missing_holdings_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="goal",
            name="target_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name="CMASnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        default=web.api.models.uuid_string, max_length=120, unique=True
                    ),
                ),
                ("name", models.CharField(default="Fraser CMA", max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_cma_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_cma_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CMAFundAssumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fund_id", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=255)),
                ("expected_return", models.DecimalField(decimal_places=8, max_digits=10)),
                ("volatility", models.DecimalField(decimal_places=8, max_digits=10)),
                ("optimizer_eligible", models.BooleanField(default=True)),
                ("is_whole_portfolio", models.BooleanField(default=False)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("asset_class_weights", models.JSONField(blank=True, default=dict)),
                ("tax_drag", models.JSONField(blank=True, default=dict)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_assumptions",
                        to="api.cmasnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "fund_id"],
            },
        ),
        migrations.CreateModel(
            name="CMACorrelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("row_fund_id", models.CharField(max_length=120)),
                ("col_fund_id", models.CharField(max_length=120)),
                ("correlation", models.DecimalField(decimal_places=5, max_digits=8)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlations",
                        to="api.cmasnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["row_fund_id", "col_fund_id"],
            },
        ),
        migrations.CreateModel(
            name="PlanningVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("state", models.JSONField(default=dict)),
                ("rationale", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_versions",
                        to="api.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        default=web.api.models.uuid_string, max_length=120, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("current", "Current"), ("stale", "Stale")],
                        default="current",
                        max_length=20,
                    ),
                ),
                ("stale_reason", models.CharField(blank=True, max_length=255)),
                ("input_snapshot", models.JSONField(default=dict)),
                ("output", models.JSONField(default=dict)),
                ("input_hash", models.CharField(max_length=64)),
                ("output_hash", models.CharField(max_length=64)),
                ("engine_version", models.CharField(max_length=120)),
                ("advisor_summary", models.TextField(blank=True)),
                ("technical_trace", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cma_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_runs",
                        to="api.cmasnapshot",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_runs",
                        to="api.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioRunLinkRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("goal_external_id", models.CharField(max_length=120)),
                ("account_external_id", models.CharField(max_length=120)),
                ("allocated_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("frontier_percentile", models.PositiveSmallIntegerField()),
                ("expected_return", models.DecimalField(decimal_places=8, max_digits=10)),
                ("volatility", models.DecimalField(decimal_places=8, max_digits=10)),
                ("allocations", models.JSONField(default=list)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.account",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.goal",
                    ),
                ),
                (
                    "portfolio_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_recommendation_rows",
                        to="api.portfoliorun",
                    ),
                ),
            ],
            options={
                "ordering": ["goal_external_id", "account_external_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="cmasnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("status",),
                name="unique_active_cma_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="cmasnapshot",
            constraint=models.UniqueConstraint(
                fields=("version",), name="unique_cma_snapshot_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="cmafundassumption",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "fund_id"), name="unique_cma_fund_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="cmacorrelation",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "row_fund_id", "col_fund_id"),
                name="unique_cma_correlation_cell",
            ),
        ),
        migrations.AddConstraint(
            model_name="planningversion",
            constraint=models.UniqueConstraint(
                fields=("household", "version"), name="unique_planning_version_per_household"
            ),
        ),
    ]
