# Generated by Django 5.2.13 on 2026-04-30 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_portfolio_v2_contract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "equity_pct",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "fixed_income_pct",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cash_pct",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "real_assets_pct",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_holdings",
                        to="api.household",
                    ),
                ),
            ],
            options={
                "ordering": ["household__display_name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "q1",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "q2",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=1
                    ),
                ),
                ("q3", models.JSONField(blank=True, default=list)),
                (
                    "q4",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=1
                    ),
                ),
                ("tolerance_score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("capacity_score", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "tolerance_descriptor",
                    models.CharField(
                        choices=[
                            ("Cautious", "Cautious"),
                            ("Conservative-balanced", "Conservative-balanced"),
                            ("Balanced", "Balanced"),
                            ("Balanced-growth", "Balanced-growth"),
                            ("Growth-oriented", "Growth-oriented"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "capacity_descriptor",
                    models.CharField(
                        choices=[
                            ("Cautious", "Cautious"),
                            ("Conservative-balanced", "Conservative-balanced"),
                            ("Balanced", "Balanced"),
                            ("Balanced-growth", "Balanced-growth"),
                            ("Growth-oriented", "Growth-oriented"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "household_descriptor",
                    models.CharField(
                        choices=[
                            ("Cautious", "Cautious"),
                            ("Conservative-balanced", "Conservative-balanced"),
                            ("Balanced", "Balanced"),
                            ("Balanced-growth", "Balanced-growth"),
                            ("Growth-oriented", "Growth-oriented"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "score_1_5",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("anchor", models.DecimalField(decimal_places=2, max_digits=5)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_profile",
                        to="api.household",
                    ),
                ),
            ],
            options={
                "ordering": ["household__display_name"],
            },
        ),
        migrations.CreateModel(
            name="GoalRiskOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "score_1_5",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "descriptor",
                    models.CharField(
                        choices=[
                            ("Cautious", "Cautious"),
                            ("Conservative-balanced", "Conservative-balanced"),
                            ("Balanced", "Balanced"),
                            ("Balanced-growth", "Balanced-growth"),
                            ("Growth-oriented", "Growth-oriented"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_risk_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_overrides",
                        to="api.goal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rationale__regex", ".{10,}")),
                        name="goal_risk_override_rationale_min_length",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HouseholdSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("realignment", "Realignment"),
                            ("cash_in", "Cash in"),
                            ("cash_out", "Cash out"),
                            ("re_link", "Re-link"),
                            ("override", "Override"),
                            ("re_goal", "Re-goal"),
                            ("restore", "Restore"),
                        ],
                        max_length=40,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("snapshot", models.JSONField(default=dict)),
                ("summary", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="household_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="api.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["household", "-created_at"], name="api_househo_househo_5bf0bb_idx"
                    )
                ],
            },
        ),
    ]
