# Generated by Django 5.2.13 on 2026-05-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_v36_ui_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("duplicate", "Duplicate"),
                    ("classified", "Classified"),
                    ("text_extracted", "Text extracted"),
                    ("ocr_required", "OCR required"),
                    ("ocr_complete", "OCR complete"),
                    ("facts_extracted", "Facts extracted"),
                    ("reconciled", "Reconciled"),
                    ("unsupported", "Unsupported"),
                    ("failed", "Failed"),
                    ("manual_entry", "Manual entry"),
                ],
                default="uploaded",
                max_length=40,
            ),
        ),
    ]
