# Generated by Django 5.2.13 on 2026-05-03 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_reviewdocument_status"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisorProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="advisor_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("disclaimer_acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disclaimer_acknowledged_version",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("tour_completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FactOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("field", models.CharField(max_length=255)),
                ("value", models.JSONField()),
                ("rationale", models.TextField(blank=True)),
                ("is_added", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fact_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_overrides",
                        to="api.reviewworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "field", "-created_at"],
                        name="api_factove_workspa_635ccc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("blocking", "Blocking"),
                            ("friction", "Friction"),
                            ("suggestion", "Suggestion"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField()),
                ("what_were_you_trying", models.TextField(blank=True)),
                ("route", models.CharField(max_length=128)),
                ("session_id", models.CharField(blank=True, max_length=64)),
                ("browser_user_agent", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("triaged", "Triaged"),
                            ("in_progress", "In progress"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                ("ops_notes", models.TextField(blank=True)),
                ("linear_issue_url", models.URLField(blank=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="api_feedbac_status_019dec_idx"
                    ),
                    models.Index(
                        fields=["severity", "-created_at"], name="api_feedbac_severit_0f19e2_idx"
                    ),
                    models.Index(
                        fields=["advisor", "-created_at"], name="api_feedbac_advisor_ccfa67_idx"
                    ),
                ],
            },
        ),
    ]
