# Generated by Codex on 2026-04-29

from django.db import migrations


def add_audit_immutability(apps, schema_editor):  # noqa: ARG001
    vendor = schema_editor.connection.vendor
    if vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION audit_event_immutable()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'Audit events are immutable';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS audit_event_no_update ON audit_auditevent;
        CREATE TRIGGER audit_event_no_update
        BEFORE UPDATE ON audit_auditevent
        FOR EACH ROW EXECUTE FUNCTION audit_event_immutable();
        """
    )
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS audit_event_no_delete ON audit_auditevent;
        CREATE TRIGGER audit_event_no_delete
        BEFORE DELETE ON audit_auditevent
        FOR EACH ROW EXECUTE FUNCTION audit_event_immutable();
        """
    )


def drop_audit_immutability(apps, schema_editor):  # noqa: ARG001
    vendor = schema_editor.connection.vendor
    if vendor != "postgresql":
        return
    schema_editor.execute("DROP TRIGGER IF EXISTS audit_event_no_update ON audit_auditevent;")
    schema_editor.execute("DROP TRIGGER IF EXISTS audit_event_no_delete ON audit_auditevent;")
    schema_editor.execute("DROP FUNCTION IF EXISTS audit_event_immutable();")


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_audit_immutability, drop_audit_immutability),
    ]
