"""URL config for the Phase 1 scaffold."""

from __future__ import annotations

from django.contrib import admin
from django.urls import path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from web.api import preview_views, views, wizard_views

urlpatterns = [
    path("admin/", admin.site.urls),
    # OpenAPI schema + interactive docs (locked decision #24b).
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    path(
        "api/redoc/",
        SpectacularRedocView.as_view(url_name="api-schema"),
        name="api-redoc",
    ),
    path("api/auth/login/", views.LocalLoginView.as_view(), name="local-login"),
    path("api/auth/logout/", views.LocalLogoutView.as_view(), name="local-logout"),
    path("api/session/", views.SessionView.as_view(), name="session"),
    path(
        "api/disclaimer/acknowledge/",
        views.DisclaimerAcknowledgeView.as_view(),
        name="disclaimer-acknowledge",
    ),
    path(
        "api/tour/complete/",
        views.TourCompleteView.as_view(),
        name="tour-complete",
    ),
    path(
        "api/feedback/",
        views.FeedbackSubmitView.as_view(),
        name="feedback-submit",
    ),
    path(
        "api/feedback/report/",
        views.FeedbackReportView.as_view(),
        name="feedback-report",
    ),
    path(
        "api/feedback/<int:feedback_id>/",
        views.FeedbackUpdateView.as_view(),
        name="feedback-update",
    ),
    path("api/clients/", views.ClientListView.as_view(), name="client-list"),
    path("api/clients/<str:household_id>/", views.ClientDetailView.as_view(), name="client-detail"),
    path(
        "api/clients/<str:household_id>/generate-portfolio/",
        views.GeneratePortfolioView.as_view(),
        name="generate-portfolio",
    ),
    path(
        "api/clients/<str:household_id>/portfolio-runs/",
        views.PortfolioRunListView.as_view(),
        name="portfolio-run-list",
    ),
    path(
        "api/clients/<str:household_id>/portfolio-runs/<str:run_id>/decline/",
        views.PortfolioRunDeclineView.as_view(),
        name="portfolio-run-decline",
    ),
    path(
        "api/clients/<str:household_id>/portfolio-runs/<str:run_id>/audit-export/",
        views.PortfolioRunAuditExportView.as_view(),
        name="portfolio-run-audit-export",
    ),
    path(
        "api/clients/<str:household_id>/planning-versions/",
        views.PlanningVersionListView.as_view(),
        name="planning-version-list",
    ),
    path("api/cma/snapshots/", views.CMASnapshotListView.as_view(), name="cma-snapshot-list"),
    path(
        "api/cma/snapshots/<str:snapshot_id>/",
        views.CMASnapshotDetailView.as_view(),
        name="cma-snapshot-detail",
    ),
    path("api/cma/active/", views.CMAActiveView.as_view(), name="cma-active"),
    path("api/cma/audit/", views.CMAAuditView.as_view(), name="cma-audit"),
    path(
        "api/cma/snapshots/<str:snapshot_id>/publish/",
        views.CMASnapshotPublishView.as_view(),
        name="cma-snapshot-publish",
    ),
    path(
        "api/cma/snapshots/<str:snapshot_id>/frontier/",
        views.CMAFrontierView.as_view(),
        name="cma-frontier",
    ),
    path(
        "api/review-workspaces/",
        views.ReviewWorkspaceListCreateView.as_view(),
        name="review-workspace-list",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/",
        views.ReviewWorkspaceDetailView.as_view(),
        name="review-workspace-detail",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/upload/",
        views.ReviewWorkspaceUploadView.as_view(),
        name="review-workspace-upload",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/documents/<int:document_id>/",
        views.ReviewDocumentDetailView.as_view(),
        name="review-document-detail",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/documents/<int:document_id>/retry/",
        views.ReviewDocumentRetryView.as_view(),
        name="review-document-retry",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/documents/<int:document_id>/manual-entry/",
        views.ReviewDocumentManualEntryView.as_view(),
        name="review-document-manual-entry",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/facts/",
        views.ReviewWorkspaceFactsView.as_view(),
        name="review-workspace-facts",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/facts/<int:fact_id>/evidence/",
        views.ReviewFactEvidenceView.as_view(),
        name="review-fact-evidence",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/state/",
        views.ReviewWorkspaceStateView.as_view(),
        name="review-workspace-state",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/conflicts/resolve/",
        views.ReviewWorkspaceConflictResolveView.as_view(),
        name="review-workspace-conflict-resolve",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/conflicts/bulk-resolve/",
        views.ReviewWorkspaceConflictBulkResolveView.as_view(),
        name="review-workspace-conflict-bulk-resolve",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/facts/override/",
        views.ReviewWorkspaceFactOverrideView.as_view(),
        name="review-workspace-fact-override",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/approve-section/",
        views.ReviewWorkspaceSectionApprovalView.as_view(),
        name="review-workspace-approve-section",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/matches/",
        views.ReviewWorkspaceMatchView.as_view(),
        name="review-workspace-matches",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/manual-reconcile/",
        views.ReviewWorkspaceManualReconcileView.as_view(),
        name="review-workspace-manual-reconcile",
    ),
    path(
        "api/review-workspaces/<str:workspace_id>/commit/",
        views.ReviewWorkspaceCommitView.as_view(),
        name="review-workspace-commit",
    ),
    # ---- Phase R1 preview endpoints (read-only engine wrappers) ----
    path(
        "api/preview/risk-profile/",
        preview_views.RiskProfilePreviewView.as_view(),
        name="preview-risk-profile",
    ),
    path(
        "api/preview/goal-score/",
        preview_views.GoalScorePreviewView.as_view(),
        name="preview-goal-score",
    ),
    path(
        "api/preview/sleeve-mix/",
        preview_views.SleeveMixPreviewView.as_view(),
        name="preview-sleeve-mix",
    ),
    path(
        "api/preview/projection/",
        preview_views.ProjectionPreviewView.as_view(),
        name="preview-projection",
    ),
    path(
        "api/preview/projection-paths/",
        preview_views.ProjectionPathsPreviewView.as_view(),
        name="preview-projection-paths",
    ),
    path(
        "api/preview/probability/",
        preview_views.ProbabilityPreviewView.as_view(),
        name="preview-probability",
    ),
    path(
        "api/preview/optimizer-output/",
        preview_views.OptimizerOutputPreviewView.as_view(),
        name="preview-optimizer-output",
    ),
    path(
        "api/preview/moves/",
        preview_views.MovesPreviewView.as_view(),
        name="preview-moves",
    ),
    path(
        "api/preview/blended-account-risk/",
        preview_views.BlendedAccountRiskPreviewView.as_view(),
        name="preview-blended-account-risk",
    ),
    path(
        "api/preview/collapse-suggestion/",
        preview_views.CollapseSuggestionPreviewView.as_view(),
        name="preview-collapse-suggestion",
    ),
    path(
        "api/treemap/",
        preview_views.TreemapDataView.as_view(),
        name="treemap-data",
    ),
    # ---- Phase R1 state-changing endpoints ----
    path(
        "api/households/wizard/",
        wizard_views.WizardCommitView.as_view(),
        name="wizard-commit",
    ),
    path(
        "api/households/<str:household_id>/realignment/",
        wizard_views.RealignmentView.as_view(),
        name="household-realignment",
    ),
    path(
        "api/households/<str:household_id>/snapshots/",
        wizard_views.HouseholdSnapshotListView.as_view(),
        name="household-snapshots",
    ),
    path(
        "api/households/<str:household_id>/snapshots/<int:snapshot_id>/",
        wizard_views.HouseholdSnapshotDetailView.as_view(),
        name="household-snapshot-detail",
    ),
    path(
        "api/households/<str:household_id>/snapshots/<int:snapshot_id>/restore/",
        wizard_views.HouseholdSnapshotRestoreView.as_view(),
        name="household-snapshot-restore",
    ),
    path(
        "api/goals/<str:goal_id>/override/",
        wizard_views.GoalRiskOverrideCreateView.as_view(),
        name="goal-risk-override-create",
    ),
    path(
        "api/goals/<str:goal_id>/overrides/",
        wizard_views.GoalRiskOverrideListView.as_view(),
        name="goal-risk-override-list",
    ),
    path(
        "api/households/<str:household_id>/external-holdings/",
        wizard_views.ExternalHoldingListCreateView.as_view(),
        name="external-holdings-list",
    ),
    path(
        "api/households/<str:household_id>/external-holdings/<int:holding_id>/",
        wizard_views.ExternalHoldingDetailView.as_view(),
        name="external-holdings-detail",
    ),
]
