/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["clients_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{household_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["clients_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{household_id}/generate-portfolio/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clients_generate_portfolio_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{household_id}/planning-versions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["clients_planning_versions_retrieve"];
        put?: never;
        post: operations["clients_planning_versions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{household_id}/portfolio-runs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["clients_portfolio_runs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{household_id}/portfolio-runs/{run_id}/audit-export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["clients_portfolio_runs_audit_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{household_id}/portfolio-runs/{run_id}/decline/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clients_portfolio_runs_decline_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cma/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cma_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cma/audit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cma_audit_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cma/snapshots/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cma_snapshots_retrieve"];
        put?: never;
        post: operations["cma_snapshots_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cma/snapshots/{snapshot_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cma_snapshots_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["cma_snapshots_partial_update"];
        trace?: never;
    };
    "/api/cma/snapshots/{snapshot_id}/frontier/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cma_snapshots_frontier_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cma/snapshots/{snapshot_id}/publish/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cma_snapshots_publish_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{goal_id}/override/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an advisor risk override on a goal (canon 1-5 + descriptor)
         * @description Per locked decision #6, override operates exclusively on the canon 1-5 + descriptor surface. Per locked decision #37, every save fires an AuditEvent with kind 'goal_risk_override_created' capturing before/after canon score + descriptor + rationale.
         */
        post: operations["goals_override_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{goal_id}/overrides/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List goal risk override history (read-only)
         * @description GET /api/goals/{goal_id}/overrides/
         */
        get: operations["goals_overrides_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{household_id}/external-holdings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List external holdings for a household
         * @description GET/POST /api/households/{household_id}/external-holdings/
         */
        get: operations["households_external_holdings_retrieve"];
        put?: never;
        /**
         * List external holdings for a household
         * @description GET/POST /api/households/{household_id}/external-holdings/
         */
        post: operations["households_external_holdings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{household_id}/external-holdings/{holding_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Update / delete an external holding
         * @description PATCH / DELETE /api/households/{household_id}/external-holdings/{holding_id}/
         */
        delete: operations["households_external_holdings_destroy"];
        options?: never;
        head?: never;
        /**
         * Update / delete an external holding
         * @description PATCH / DELETE /api/households/{household_id}/external-holdings/{holding_id}/
         */
        patch: operations["households_external_holdings_partial_update"];
        trace?: never;
    };
    "/api/households/{household_id}/realignment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-goal account-to-goal allocations (label-only; canon §6.3a)
         * @description Per canon §6.3a + locked decision #15, this endpoint adjusts the labels on each account's goal allocations — it never moves money or changes underlying holdings. Server creates a 'before' HouseholdSnapshot, applies the relabel, computes 'after' snapshot, fires audit, and returns big-shift indicators (>5pt blended account risk delta).
         */
        post: operations["households_realignment_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{household_id}/snapshots/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List household snapshots (history tab)
         * @description GET /api/households/{household_id}/snapshots/
         */
        get: operations["households_snapshots_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{household_id}/snapshots/{snapshot_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a household snapshot detail
         * @description GET /api/households/{household_id}/snapshots/{snapshot_id}/
         */
        get: operations["households_snapshots_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/{household_id}/snapshots/{snapshot_id}/restore/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a household to a prior snapshot (creates a new 'restore' snapshot)
         * @description Per locked decision #36, restore creates a NEW snapshot tagged 'restore' rather than rewinding, so the chain stays linear and reversible. The restore replays the snapshot's allocation amounts onto current GoalAccountLink rows.
         */
        post: operations["households_snapshots_restore_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/wizard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new household via the 5-step wizard (locked decision #7)
         * @description Doc-drop is the primary onboarding path; this wizard is the fallback for edge cases per canon §6.7. Server creates Household + Person(s) + Account(s) + Goal(s) + GoalAccountLink(s) + RiskProfile + ExternalHolding(s) atomically inside transaction.atomic per locked decision #30.
         */
        post: operations["households_wizard_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/blended-account-risk/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Blended account risk before/after candidate goal-amount edit
         * @description Used by the realignment modal: when the advisor proposes new goal allocations on an account, this endpoint reports whether the blended account risk would shift > 5pts (canon §6.3a banner threshold).
         */
        post: operations["preview_blended_account_risk_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/collapse-suggestion/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * FoF collapse suggestion for a building-block blend (canon §4.3b)
         * @description POST /api/preview/collapse-suggestion/
         */
        post: operations["preview_collapse_suggestion_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/goal-score/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve goal-level risk score (canon 1-5 + descriptor)
         * @description Live wizard step 3 recompute. Per locked decision #6, the response intentionally omits the internal Goal_50 number; the advisor sees only the canon 1-5 score + descriptor + horizon-cap-binding flag + override-active flag + derivation breakdown (anchor / imp_shift / size_shift).
         */
        post: operations["preview_goal_score_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/moves/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebalance moves to bring current to ideal (canon §8.10)
         * @description POST /api/preview/moves/
         */
        post: operations["preview_moves_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/optimizer-output/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimizer output widget — improvement % at P_score downside
         * @description Mockup v34: improvement_pct = (ideal_low − current_low) / current_low × 100, where p = goal_risk_score / 5 → percentile.
         */
        post: operations["preview_optimizer_output_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/probability/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Probability that S_T >= target (lognormal)
         * @description Drives the fan-chart hover crosshair callout per v36 mockup §35.
         */
        post: operations["preview_probability_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/projection/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lognormal projection bands at horizon
         * @description POST /api/preview/projection/
         */
        post: operations["preview_projection_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/projection-paths/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lognormal paths along constant-percentile curves
         * @description POST /api/preview/projection-paths/
         */
        post: operations["preview_projection_paths_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/risk-profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute household risk profile from Q1-Q4
         * @description Wizard step 2 live recompute. Returns canon 1-5 + descriptor + anchor + tolerance/capacity scores + consistency flags. Per locked decision #6, Goal_50 / T / C are surfaced as advisor-transparent intermediates here (T/C in 0-100, anchor in 0-50).
         */
        post: operations["preview_risk_profile_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/sleeve-mix/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sleeve mix at canonical risk score
         * @description Returns the calibration-reference SLEEVE_REF_POINTS mix for a canon 1-5 score. NOT the optimizer output — the optimizer uses frontier optimization (canon §4.1). This endpoint serves the advisor methodology page + visual sleeve-mix preview, not the production allocation.
         */
        post: operations["preview_sleeve_mix_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["review_workspaces_retrieve"];
        put?: never;
        post: operations["review_workspaces_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["review_workspaces_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/approve-section/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["review_workspaces_approve_section_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/commit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["review_workspaces_commit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/conflicts/resolve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/review-workspaces/<wsid>/conflicts/resolve/ — Phase 5a.
         *
         *     Body: {field, chosen_fact_id, rationale, evidence_ack}.
         *     Records the advisor's chosen candidate + rationale + evidence
         *     acknowledgement on the workspace conflict slot. Atomic +
         *     select_for_update on the workspace; serializes concurrent
         *     advisor calls. Re-runs section-approval blocker check + flips
         *     affected approvals to NEEDS_ATTENTION (mirrors
         *     ReviewWorkspaceStateView.patch behavior). Emits exactly one
         *     `review_conflict_resolved` audit event per locked decision #37.
         *
         *     PII discipline (canon §11.8.3): the rationale text is persisted
         *     on the reviewed_state row (advisor-scoped) but NEVER copied into
         *     audit-event metadata; metadata records only `rationale_len` so
         *     the immutable audit row stays free of advisor-typed content
         *     that could reference real PII.
         */
        post: operations["review_workspaces_conflicts_resolve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/documents/{document_id}/manual-entry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Advisor escape hatch when automated extraction can't recover.
         *
         *     Marks the document as `manual_entry`, leaving the workspace's
         *     reconcile path to skip it (no fact contributions). The advisor
         *     will fill the missing fields by hand via the review-screen state
         *     editor (PATCH /state/). Distinct from FAILED so the audit trail
         *     captures a deliberate advisor decision rather than an extraction
         *     error.
         */
        post: operations["review_workspaces_documents_manual_entry_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/documents/{document_id}/retry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["review_workspaces_documents_retry_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/facts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["review_workspaces_facts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/facts/{fact_id}/evidence/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["review_workspaces_facts_evidence_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/manual-reconcile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["review_workspaces_manual_reconcile_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/matches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["review_workspaces_matches_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/state/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["review_workspaces_state_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["review_workspaces_state_partial_update"];
        trace?: never;
    };
    "/api/review-workspaces/{workspace_id}/upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["review_workspaces_upload_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treemap/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Treemap hierarchical data for HouseholdRoute
         * @description Returns hierarchical {id, label, value, color, children[]} per the requested mode: by_account / by_goal / by_fund / by_asset. Frontend (d3-hierarchy) computes the squarified layout.
         */
        get: operations["treemap_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `RRSP` - RRSP
         *     * `TFSA` - TFSA
         *     * `RESP` - RESP
         *     * `RDSP` - RDSP
         *     * `FHSA` - FHSA
         *     * `Non-Registered` - Non-Registered
         *     * `LIRA` - LIRA
         *     * `RRIF` - RRIF
         *     * `Corporate` - Corporate
         * @enum {string}
         */
        AccountTypeEnum: "RRSP" | "TFSA" | "RESP" | "RDSP" | "FHSA" | "Non-Registered" | "LIRA" | "RRIF" | "Corporate";
        BlendedAccountRiskRequestRequest: {
            household_id: string;
            account_id: string;
            candidate_goal_amounts: {
                [key: string]: number;
            };
        };
        /** @description Body: blend = {fund_id: weight}, threshold optional (default 0.92). */
        CollapseSuggestionRequestRequest: {
            blend: {
                [key: string]: number;
            };
            /**
             * Format: double
             * @default 0.92
             */
            threshold: number;
        };
        /**
         * @description * `Cautious` - Cautious
         *     * `Conservative-balanced` - Conservative-balanced
         *     * `Balanced` - Balanced
         *     * `Balanced-growth` - Balanced-growth
         *     * `Growth-oriented` - Growth-oriented
         * @enum {string}
         */
        DescriptorEnum: "Cautious" | "Conservative-balanced" | "Balanced" | "Balanced-growth" | "Growth-oriented";
        GoalRiskOverrideRequestRequest: {
            score_1_5: number;
            descriptor: components["schemas"]["DescriptorEnum"];
            rationale: string;
        };
        GoalScoreOverrideRequest: {
            score_1_5: number;
            descriptor: components["schemas"]["DescriptorEnum"];
            rationale: string;
        };
        /**
         * @description Per locked decision #6: API takes canon-shaped inputs, never Goal_50.
         *
         *     The server computes Goal_50 internally from anchor + tier + size and
         *     returns canon 1-5 + descriptor + flags + derivation breakdown.
         */
        GoalScoreRequestRequest: {
            /** Format: double */
            anchor: number;
            necessity_score?: number | null;
            /** Format: double */
            goal_amount: number;
            /** Format: double */
            household_aum: number;
            /** Format: double */
            horizon_years: number;
            override?: components["schemas"]["GoalScoreOverrideRequest"] | null;
        };
        /**
         * @description * `single` - single
         *     * `couple` - couple
         * @enum {string}
         */
        HouseholdTypeEnum: "single" | "couple";
        /**
         * @description * `ideal` - ideal
         *     * `current` - current
         * @enum {string}
         */
        ModeEnum: "ideal" | "current";
        MovesRequestRequest: {
            household_id: string;
            goal_id: string;
        };
        OptimizerOutputRequestRequest: {
            household_id: string;
            goal_id: string;
        };
        ProbabilityRequestRequest: {
            /** Format: double */
            start: number;
            score_1_5: number;
            /** Format: double */
            horizon_years: number;
            /** Format: double */
            target: number;
            /** @default ideal */
            mode: components["schemas"]["ModeEnum"];
            /** @default false */
            is_external: boolean;
        };
        ProjectionPathsRequestRequest: {
            /** Format: double */
            start: number;
            score_1_5: number;
            /** Format: double */
            horizon_years: number;
            percentiles: number[];
            /** @default 50 */
            n_steps: number;
            /** @default ideal */
            mode: components["schemas"]["ModeEnum"];
            /** @default false */
            is_external: boolean;
        };
        ProjectionRequestRequest: {
            /** Format: double */
            start: number;
            score_1_5: number;
            /** Format: double */
            horizon_years: number;
            /** @default ideal */
            mode: components["schemas"]["ModeEnum"];
            /** @default false */
            is_external: boolean;
            /** @default want */
            tier: components["schemas"]["TierEnum"];
        };
        /**
         * @description * `A` - A
         *     * `B` - B
         *     * `C` - C
         *     * `D` - D
         * @enum {string}
         */
        Q2Enum: "A" | "B" | "C" | "D";
        /**
         * @description * `A` - A
         *     * `B` - B
         *     * `C` - C
         *     * `D` - D
         * @enum {string}
         */
        Q4Enum: "A" | "B" | "C" | "D";
        /**
         * @description Locked decision #15 + canon §6.3a: re-goaling is label-only.
         *
         *     Body shape: ``{account_goal_amounts: {acct_external_id: {goal_external_id: amount}}}``.
         *     Server enforces that each account's leg sums equal the account total
         *     (no money created/destroyed). The mutation updates GoalAccountLink
         *     rows; underlying Holdings are never touched.
         */
        RealignmentRequestRequest: {
            account_goal_amounts: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        RiskProfileRequestRequest: {
            q1: number;
            q2: components["schemas"]["Q2Enum"];
            q3?: string[];
            q4: components["schemas"]["Q4Enum"];
        };
        RiskProfileResponse: {
            /** Format: double */
            tolerance_score: number;
            /** Format: double */
            capacity_score: number;
            tolerance_descriptor: string;
            capacity_descriptor: string;
            household_descriptor: string;
            score_1_5: number;
            /** Format: double */
            anchor: number;
            flags: string[];
        };
        SleeveMixRequestRequest: {
            score_1_5: number;
        };
        /**
         * @description * `need` - need
         *     * `want` - want
         *     * `wish` - wish
         *     * `unsure` - unsure
         * @enum {string}
         */
        TierEnum: "need" | "want" | "wish" | "unsure";
        WizardAccountRequest: {
            account_type: components["schemas"]["AccountTypeEnum"];
            /** Format: decimal */
            current_value: string;
            /** @default  */
            custodian: string;
        };
        /**
         * @description Locked decision #7: wizard is the fallback path. Doc-drop is primary.
         *
         *     Server validates the full wizard payload, creates Household + Person(s)
         *     + Account(s) + Goal(s) + GoalAccountLink(s) + RiskProfile +
         *     ExternalHolding(s) atomically.
         */
        WizardCommitRequest: {
            display_name: string;
            household_type: components["schemas"]["HouseholdTypeEnum"];
            members: components["schemas"]["WizardMemberRequest"][];
            /** @default  */
            notes: string;
            risk_profile: components["schemas"]["WizardRiskProfileRequest"];
            accounts: components["schemas"]["WizardAccountRequest"][];
            goals: components["schemas"]["WizardGoalRequest"][];
            external_holdings?: components["schemas"]["WizardExternalHoldingRequest"][];
        };
        WizardExternalHoldingRequest: {
            /** @default  */
            name: string;
            /** Format: decimal */
            value: string;
            /** Format: decimal */
            equity_pct: string;
            /** Format: decimal */
            fixed_income_pct: string;
            /** Format: decimal */
            cash_pct: string;
            /** Format: decimal */
            real_assets_pct: string;
        };
        WizardGoalLegRequest: {
            account_index: number;
            /** Format: decimal */
            allocated_amount: string;
        };
        WizardGoalRequest: {
            name: string;
            /** Format: date */
            target_date: string;
            necessity_score: number;
            /** Format: decimal */
            target_amount?: string | null;
            legs: components["schemas"]["WizardGoalLegRequest"][];
        };
        WizardMemberRequest: {
            name: string;
            /** Format: date */
            dob: string;
        };
        WizardRiskProfileRequest: {
            q1: number;
            q2: components["schemas"]["Q2Enum"];
            q3?: string[];
            q4: components["schemas"]["Q4Enum"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clients_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clients_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clients_generate_portfolio_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clients_planning_versions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clients_planning_versions_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clients_portfolio_runs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clients_portfolio_runs_audit_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clients_portfolio_runs_decline_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cma_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cma_audit_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cma_snapshots_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cma_snapshots_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cma_snapshots_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cma_snapshots_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cma_snapshots_frontier_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cma_snapshots_publish_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    goals_override_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalRiskOverrideRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GoalRiskOverrideRequestRequest"];
                "multipart/form-data": components["schemas"]["GoalRiskOverrideRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    goals_overrides_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    households_external_holdings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    households_external_holdings_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    households_external_holdings_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    households_external_holdings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    households_realignment_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RealignmentRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RealignmentRequestRequest"];
                "multipart/form-data": components["schemas"]["RealignmentRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    households_snapshots_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    households_snapshots_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    households_snapshots_restore_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    households_wizard_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WizardCommitRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WizardCommitRequest"];
                "multipart/form-data": components["schemas"]["WizardCommitRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_blended_account_risk_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlendedAccountRiskRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BlendedAccountRiskRequestRequest"];
                "multipart/form-data": components["schemas"]["BlendedAccountRiskRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_collapse_suggestion_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollapseSuggestionRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CollapseSuggestionRequestRequest"];
                "multipart/form-data": components["schemas"]["CollapseSuggestionRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_goal_score_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalScoreRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GoalScoreRequestRequest"];
                "multipart/form-data": components["schemas"]["GoalScoreRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_moves_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovesRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MovesRequestRequest"];
                "multipart/form-data": components["schemas"]["MovesRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_optimizer_output_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizerOutputRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OptimizerOutputRequestRequest"];
                "multipart/form-data": components["schemas"]["OptimizerOutputRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_probability_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbabilityRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProbabilityRequestRequest"];
                "multipart/form-data": components["schemas"]["ProbabilityRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_projection_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectionRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectionRequestRequest"];
                "multipart/form-data": components["schemas"]["ProjectionRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_projection_paths_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectionPathsRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectionPathsRequestRequest"];
                "multipart/form-data": components["schemas"]["ProjectionPathsRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_risk_profile_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskProfileRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RiskProfileRequestRequest"];
                "multipart/form-data": components["schemas"]["RiskProfileRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskProfileResponse"];
                };
            };
        };
    };
    preview_sleeve_mix_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SleeveMixRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SleeveMixRequestRequest"];
                "multipart/form-data": components["schemas"]["SleeveMixRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_approve_section_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_commit_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_conflicts_resolve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_documents_manual_entry_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_documents_retry_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_facts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_facts_evidence_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: number;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_manual_reconcile_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_matches_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_state_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_state_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_workspaces_upload_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    treemap_retrieve: {
        parameters: {
            query: {
                household_id: string;
                mode?: "by_account" | "by_asset" | "by_fund" | "by_goal";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
